# <==============================================================>

#   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— 
#   â–ˆâ–ˆâ•”â•â•â•â•â•â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
#   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•
#   â•šâ•â•â•â•â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â• 
#   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     
#   â•šâ•â•â•â•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•šâ•â•     
                                                            
# <==============================================================>
#                       @Author: TheWisker
# <==============================================================>
#                  Starship prompt configuration
# <==============================================================>
#  Prompt wide:
# <==============================================================>
format = """
$username\
$hostname\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$openstack\
$nats\
$crystal\
$container\
$sudo\
$battery\
$cmd_duration\
$jobs\
$line_break\
$character"""
scan_timeout = 25
add_newline = true
command_timeout = 350
right_format = "$time"
follow_symlinks = true
# <==============================================================>
#                            First row
# <==============================================================>
#  First param:
# <==============================================================>
[username]
show_always = true
style_root = "bold red"
style_user = "bold purple"
format = " [â•­â”€$user]($style)"
# <==============================================================>
#  Second param:
# <==============================================================>
[hostname]
trim_at = ""
ssh_only = false
style = "bold dimmed blue"
format = "@[$hostname]($style)([ $ssh_symbol]($style))"
# <==============================================================>
#  Third param:
# <==============================================================>
[directory]
read_only = "r."
home_symbol = "~"
style = "bold yellow"
truncation_length = 0
use_os_path_sep = true
truncate_to_repo = true
repo_root_style = "bold yellow"
read_only_style = "bold dimmed yellow"
format = " in [$read_only]($read_only_style)[$path]($style)"
repo_root_format = " in [repo:]($repo_root_style) ([$read_only](bold dimmed yellow))[$repo_root]($repo_root_style)[$path](bold dimmed yellow)"
# <==============================================================>
[directory.substitutions]
'/mnt/media/' = '//:'
# <==============================================================>
#  Fourth param:
# <==============================================================>
#  Version Control Context
# <==============================================================>
[git_branch]
symbol = "ï˜"
style = "bold yellow"
format = " on [$symbol $branch(:$remote_branch)]($style)"
# <==============================================================>
[git_state]
style = "bold yellow"
format = '( \([$state( $progress_current/$progress_total)]($style)\))'
# <==============================================================>
[git_status]
ahead = "${count}â‡¡"
behind = "${count}â‡£"
staged = "${count}ğŸ‘"
style = "bold yellow"
stashed = "${count}ğŸ“¦"
renamed = "${count}ğŸ‘…"
deleted = "${count}ğŸ—‘ï¸"
modified = "${count}ğŸ“"
untracked = "${count}ğŸ”"
conflicted = "${count}âš”ï¸"
up_to_date = "${count}âœ”ï¸"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
format = "( with [$conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind]($style))"
# <==============================================================>
[vcsh]
symbol = ''
style = "bold yellow"
format = " vcsh [$symbol$repo]($style)"
# <==============================================================>
#  Fifth param:
# <==============================================================>
[sudo]
symbol = "root"
disabled = false # true by default
style = "bold blink bright-red"
format = " as [$symbol]($style)"
# <==============================================================>
#  Sixth param:
# <==============================================================>
[battery]
full_symbol = "ï•¸"
empty_symbol = "ó°‚"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"
format = "( [$symbol$percentage]($style))"
# <==============================================================>
[[battery.display]]
threshold = 25
style = "bold red"
# <==============================================================>
[[battery.display]]
threshold = 50
style = "bold yellow"
# <==============================================================>
#  Seventh param:
# <==============================================================>
[cmd_duration]
min_time = 1
style = "bold cyan"
show_milliseconds = true
format = " took [$duration]($style)"
# <==============================================================>
#  Eighth param:
# <==============================================================>
[jobs]
symbol = "+"
style = "bold red"
symbol_threshold = 1
number_threshold = 2
format = " [$symbol$number]($style)"
# <==============================================================>
#                           Second row
# <==============================================================>
#  First param:
# <==============================================================>
[character]
format = "$symbol "
error_symbol = " [â•°â”€âœ˜](bold red)"
success_symbol = " [â•°â”€Î»](bold purple)"
# <==============================================================>
#  Contextual Information:
# <==============================================================>
[aws]
disabled = true
# <==============================================================>
[buf]
symbol = 'ğŸƒ'
style = "bold blue"
version_format = "v${raw}"
format = " with [$symbol($version)]($style)"
# <==============================================================>
[bun]
symbol = 'ğŸ¥Ÿ'
style = "bold blue"
version_format = "v${raw}"
format = " with [$symbol($version(-$name))]($style)"
# <==============================================================>
[c]
symbol = 'C'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[cmake]
symbol = 'â–³'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[cobol]
symbol = 'âš™ï¸'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[conda]
symbol = 'ğŸ…’'
style = "bold blue"
format = " via [$symbol$environment)]($style)"
# <==============================================================>
[container]
symbol = 'â¬¢'
style = "bold blue"
format = ' on [$symbol\[$name\]]($style)'
# <==============================================================>
[crystal]
symbol = 'ğŸ”®'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[daml]
symbol = 'Î›'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[dart]
symbol = 'ğŸ¯'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[deno]
symbol = 'ğŸ¦•'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[docker_context]
symbol = 'ğŸ³'
style = "bold blue"
format = " via [$symbol$context]($style)"
# <==============================================================>
[dotnet]
symbol = '.NET'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)( ğŸ¯$tfm)]($style)"
# <==============================================================>
[elixir]
symbol = 'ğŸ’§'
style = "bold blue"
version_format = "v${raw}"
format = ' via [$symbol($version \(OTP $otp_version\))]($style)'
# <==============================================================>
[elm]
symbol = 'ğŸŒ³'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[erlang]
symbol = 'î±'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[fennel]
symbol = 'ğŸ§…'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[gcloud]
disabled = true
# <==============================================================>
[gleam]
symbol = 'â­'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[golang]
symbol = 'ğŸ¹'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[guix_shell]
symbol = 'Gx'
style = "bold blue"
format = " via [$symbol]($style)"
# <==============================================================>
[gradle]
symbol = 'ğŸ…¶'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[haskell]
symbol = 'Î»'
style = "bold blue"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[haxe]
symbol = 'âŒ˜'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[helm]
symbol = 'âˆ'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[java]
symbol = 'â˜•'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[julia]
symbol = 'à®ƒ'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[kotlin]
symbol = 'ğŸ…º'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[lua]
symbol = 'ğŸŒ™'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[meson]
symbol = 'â¬¢'
style = "bold blue"
format = " via [$symbol$project($style)"
# <==============================================================>
[nats]
symbol = 'âœ‰ï¸'
style = "bold blue"
format = " on [$symbol$name]($style)"
# <==============================================================>
[nim]
symbol = 'ğŸ‘‘'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol( $version)]($style)"
# <==============================================================>
[nix_shell]
symbol = 'â„ï¸'
style = "bold blue"
format = ' via [$symbol$state( \($name\))]($style)'
# <==============================================================>
[nodejs]
symbol = 'îœ˜'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[ocaml]
symbol = 'ğŸ«'
style = "bold blue"
version_format = "v${raw}"
format = ' via [$symbol($version)( \($switch_indicator$switch_name\))]($style)'
# <==============================================================>
[odin]
symbol = 'Ã˜'
style = "bold blue"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[opa]
symbol = 'ğŸª–'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[openstack]
symbol = 'â˜ï¸'
style = "bold blue"
format = ' on [$symbol$cloud(\($project\))]($style)'
# <==============================================================>
[package]
symbol = 'ğŸ“¦'
style = "bold blue"
version_format = "v${raw}"
format = " is [$symbol$version]($style)"
# <==============================================================>
[perl]
symbol = 'âšª'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[php]
symbol = 'ğŸ˜'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[purescript]
symbol = '<=>'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[python]
symbol = 'ğŸ'
style = "bold blue"
version_format = "v${raw}"
format = ' via [$symbol$pyenv_prefix($version)( \($virtualenv\))]($style)'
# <==============================================================>
[quarto]
symbol = 'â¨'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[rlang]
symbol = 'R'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[raku]
symbol = 'ğŸ¦‹'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version(-$vm_version))]($style)"
# <==============================================================>
[red]
symbol = 'ğŸ”º'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[ruby]
symbol = 'îˆ¾'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[rust]
symbol = 'ğŸ¦€'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[scala]
symbol = 'ğŸ†‚'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[singularity]
symbol = 'Sng'
style = "bold blue"
format = ' on [$symbol\[$env\]]($style)'
# <==============================================================>
[solidity]
symbol = 'S'
style = "bold blue"
version_format = "v${major}.${minor}.${patch}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[spack]
symbol = 'ğŸ…¢'
style = "bold blue"
format = " via [$symbol$environment]($style)"
# <==============================================================>
[swift]
symbol = 'ğŸ¦'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[terraform]
symbol = 'ğŸ’ '
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol$workspace]($style)"
# <==============================================================>
[typst]
symbol = 't'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[vagrant]
symbol = 'â±'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[vlang]
symbol = 'V'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
[zig]
symbol = 'â†¯'
style = "bold blue"
version_format = "v${raw}"
format = " via [$symbol($version)]($style)"
# <==============================================================>
